// Copyright 2017-2023 @blockandpurpose.com
// SPDX-License-Identifier: Apache-2.0

export const INST_TITLE: string[] = 
['Market - Add to Cart',
'Market - Bookmark a Store',
'Market - Remove a Store Bookmark',
'Market - Remove an Item From Cart',
'Market - Update Cart Item Quantity',
'Market - Checkout Cart',
'Market - Rate a Product or Service',
'Market - Report a Problem Damaged',
'Market - Report Problem Wrong Item',
'Market - Report Problem Not Received',
'Market - Message the Seller',
'Market - Update Buyer Account Settings',
'Market - Update Seller Account Settings',
'Market - Update Tracking Information: ',
'Market - Refuse an Order: ',
'Market - Seller Issue a Refund: ',
'Market - Seller Issue a Replacement: ',
'Market - Deny Resolution Request: ',
'Market - Message the Buyer: ',
'Market - Rate a Buyer: ',
'Market - Add a New Product',
'Market - Update a Product Details',
'Market - Add a New Service',
'Market - Update a Service Details',
'Market - Delete a Product',
'Market - Delete a Service',
'Market - Search for Products',
'Market - Search for Services',
'Market - Search for Stores',
'29',
'Market - My Buyer Account',
'Market - View My Cart',
'Market - Go To Store',
'Market - View My Seller Account',
'Market - View My Seller Orders Awaiting',
'Market - View My Seller Orders Shipped',
'Market - View My Seller Orders Delivered',
'Market - View My Seller Orders Resolved',
'Market - View My Seller Orders Problem',
'Market - View My Seller Orders Refused'];

export const INST_SUB_TITLE: string[] = 
['Instructions for Adding an Item to Your Cart',
'Instructions for Bookmarking a Store',
'Instructions for Removing a Store Bookmark',
'Instructions for removing an Item from the Cart',
'Instructions for updating Cart Item Quantity',
'Instructions for Checking Out of your Cart',
'Instructions for Rating a Product or Service',
'Instructions for reporting a problem (damaged)',
'Instructions for reporting a problem (wrong item)',
'Instructions for reporting a problem (not received)',
'Instructions for messaging a Seller',
'Instructions for Updating Buyer Account Information',
'Instructions for Updating Seller Account Information',
'Instructions for Updating Seller Tracking Information',
'Instructions for Refusing an Item Order: ',
'Instructions for Seller to Issue a Refund: ',
'Instructions for Seller to Issue a Replacement: ',
'Instructions for Seller to deny a resolution request: ',
'Instructions for Messaging the Buyer: ',
'Instructions for Reviewing a Buyer: ',
'Instructions for Adding a Product: ',
'Instructions for Updating Product Details',
'Instructions for Adding a Service: ',
'Instructions for Updating Service Details',
'Instructions for Deleting a Product from Your Store: ',
'Instructions for Deleting a Service from Your Store: ',
'Instructions for Searching for Products',
'Instructions for Searching for Services',
'Instructions for Searching for Stores',
'29',
'Instructions for Viewing Your Buyer Account',
'Instructions for Viewing My Cart',
'Instructions for Viewing a Seller Store Front',
'Instructions for Getting Your Seller Account: ',
'Instructions for Getting Your Seller Orders Awaiting: ',
'Instructions for Getting Your Seller Orders Shipped: ',
'Instructions for Getting Your Seller Orders Delivered: ',
'Instructions for Getting Your Seller Orders Resolved: ',
'Instructions for Getting Your Seller Orders with Problems: ',
'Instructions for Getting Your Seller Orders Refused: '];

export const INSTRUCTION: string[] = 
['(1) Select the From Account. (2) Verfify the name and Product ID is correct. (3) Enter the number of items you wish to purchase. (4) Click Submit button to sign and submit this transaction',
'(1) Select the From Account. (2) Verify or Select the Account of the Store Owner. (3) Click Submit button to sign and submit this transaction',
'(1) Select the From Account. (2) Select the Account of the Store in which you wish to remove the bookmark. (3) Click Submit.',
'(1) Select the From Account. (2) Click Submit button to sign and submit this transaction',
'(1) Select the From Account. (2) Update the quantity of the item to purchase. (3) Click Submit button to sign and submit this transaction',
'(1) Select the From Account. (2) Enter the Delivery Address for items in your Cart. (3) Enter the Total Amount in Cart. (4) Click Submit button to sign and submit this transaction',
'(1) Select the From Account. (2) Entering a rating (1 - 5 Stars) (3) Enter a comment (optional) (4) Click submit',
'(1) Select the From Account. (2) Enter a photo or Youtube link (optional) (3) Enter a message to the seller describing the problem. (4) Click submit. ',
'(1) Select the From Account. (2) Enter a photo or Youtube link (optional) (3) Enter a message to the seller describing the problem. (4) Click submit. ',
'(1) Select the From Account. (2) Enter a photo or Youtube link (optional) (3) Enter a message to the seller describing the problem. (4) Click submit. ',
'(1) Select the From Account. (2) Enter a photo or Youtube link (optional) (3) Enter a message to the seller. (4) Click submit. ',
'(1) Select the From Account. (2) Enter a Buyer Name (3) Enter a Location. (4) Click submit. ',
'(1) Select the Account to use for this transaction. (2) Enter a Name for the Account. (3) Enter the Physical Location of the Seller. (4) Add a description of your Products and/or Services. (5) Add an Image Link/URL for your Products and/or Services. (6) Add a YouTube Video for your offerings or business. (7) Add an additional link for further information.',
'(1) Select the From Account. (2) Enter a Tracking Information. (3) Click Shipped Yes/No. (4) Click Delivered Yes/No. (5) Click Submit button to sign and submit this transaction.',
'(1) Select the From Account. (2) Click Submit button to sign and submit this transaction',
'(1) Select the From Account. (2) Click Submit button to sign and submit this transaction.',
'(1) Select the From Account. (2) Click Submit button to sign and submit this transaction.',
'(1) Select the From Account. (2) Click Submit button to sign and submit this transaction.',
'(1) Select the From Account. (2) Enter a Photo or Youtube URL. (3) Enter a message to the Buyer. (4) Click Submit button to sign and submit this transaction',
'(1) Select the From Account. (2) Select the Account for the Buyer to Rate. (3) Enter a Rating of (1 to 5) Stars. (4) Enter a text rating or leave blank. (5) Click Submit button to sign and submit this transaction',
'(1) Select the Account to use for this transaction. (2) Fill in your product details. (3) Click submit to add the new product.',
'(1) Select the From Account. (2) Enter the product details. (3) Click Submit button to sign and submit this transaction.',
'(1) Select the Account to use for this transaction. (2) Fill in your service details. (3) Click submit to add the new service.',
'(1) Select the From Account. (2) Enter the service details. (3) Click Submit button to sign and submit this transaction.',
'(1) Select the From Account to use for this transaction. (2) Verify the Product Id and Name before you Click submit. (3) Click submit when you are ready to submit this transaction.',
'(1) Select the From Account to use for this transaction. (2) Verify the Service Id and Name before you Click submit. (3) Click submit when you are ready to submit this transaction.',
'(1) Select the From Account to use for this transaction. (2) Enter up to three keywords for your search.',
'(1) Select the From Account to use for this transaction. (2) Enter up to three keywords for your search.',
'(1) Select the From Account to use for this transaction. (2) Enter up to three keywords for your search.',
'29',
'(1) Select the Account to use for this transaction. (2) Click View ',
'(1) Select the Account to use for this transaction. (2) Click View ',
'(1) Select the Account to use for this transaction. (2) Select the Account of the Store Owner. (3) Click View ',
'(1) Select the Account to use for this transaction. (2) Click View ',
'(1) Select the Account to use for this transaction. (2) Click View ',
'(1) Select the Account to use for this transaction. (2) Click View ',
'(1) Select the Account to use for this transaction. (2) Click View ',
'(1) Select the Account to use for this transaction. (2) Click View ',
'(1) Select the Account to use for this transaction. (2) Click View ',
'(1) Select the Account to use for this transaction. (2) Click View '];

export const INST_NOTE: string[] = 
['NOTE: To complete your purchase go to My Cart to Checkout. ',
'',
'',
'IMPORTANT: Remember to reload your Checkout Cart page to see updates in the the number of items before checking out.',
'IMPORTANT: Remember to reload your Checkout Cart page to see updates in the total quantity before checking out.',
'NOTE: If the total amount enter is less than the amount in your cart the checkout will be rejected.',
'NOTE: Ratings are a number between 1 and 5.',
'NOTE: If applicable send a photo to the Seller showing the problem.',
'NOTE: If applicable send a photo to the Seller showing the problem.',
'',
'',
'',
'⚠️ Please Note: Click Submit to execute this transaction. ',
'⚠️ Please Note: Click Submit to execute this transaction. ',
'⚠️ Please Note: Click Submit to execute this transaction. ',
'⚠️ Please Note: Click Submit to execute this transaction. ',
'⚠️ Please Note: Click Submit to execute this transaction. ',
'⚠️ Please Note: Click Submit to execute this transaction. ',
'⚠️ Please Note: Click Submit to execute this transaction. ',
'⚠️ Please Note: Click Submit to execute this transaction. ',
'⚠️ Please Note: Click Submit to execute this transaction. ',
'',
'⚠️ Please Note: Click Submit to execute this transaction. ',
'',
'NOTE: You will need to refresh your Seller Account Page to see these updates. ',
'NOTE: You will need to refresh your Seller Account Page to see these updates. ',
'NOTE: If your search is too broad you may receive a Your Search is too Broad warning. Try adding additional keywords for your search.',
'NOTE: If your search is too broad you may receive a Your Search is too Broad warning. Try adding additional keywords for your search.',
'NOTE: If your search is too broad you may receive a Your Search is too Broad warning. Try adding additional keywords for your search.',
'29',
'',
'',
'NOTE: Refresh this page to see updates to a Seller Store Front',
'⚠️  IMPORTANT: Go to Update Settings to Create Your Store Front. Refresh this page to see updates.',
'NOTE: Refresh this page to see updates.',
'NOTE: Refresh this page to see updates.','NOTE: Refresh this page to see updates.',
'NOTE: Refresh this page to see updates.','NOTE: Refresh this page to see updates.',
'NOTE: Refresh this page to see updates.'];


 